version: '4'

services:
  mysql:
    image: mysql:8.3.0
    container_name: scm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: scm_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql